### ISSUE TITLE
Ionic Angular Integration?

### ISSUE THREAD

**Issue by carloarrogante** [ludufre/capacitor-screenshot#2]
Been following this one, however, is it possible to use this in Ionic?

> node_modules_capacitor-screenshot_dist_esm_web_js.js:2 ERROR Error: Uncaught (in promise): Error: Method not implemented.
Error: Method not implemented.

**Comment by ludufre** [comment]
This plugin only works on Mobile. Are you trying Ionic Lab or so?

**Comment by carloarrogante** [comment]
Hi! No, this one is integrate in our ionic project and the same problem shows when compiled / build into apk.

**Comment by carloarrogante** [comment]
Here's a sample block of our code, we might be using this wrong also. 
![image](https://user-images.githubusercontent.com/50087958/203587483-16318a63-1268-4f85-8d68-8f680ce3335c.png)

**Comment by paulstelzer** [comment]
I am also using this plugin and do not have any issues

```
import { Screenshot } from 'capacitor-screenshot';

@Injectable({
  providedIn: 'root',
})
export class ScreenshotService {

async getScreenshot() {
  const { base64 } = await Screenshot.take();

  const data = `data:image/png;base64,${base64}`,
}

}
```

**Comment by paulstelzer** [comment]
FYI, the plugin is only working when compiled as android / ios app and not in browser (web is not implemented, just like the error said)
