### ISSUE TITLE
Can I get a screenshot of the desktop

### ISSUE THREAD

**Issue by jipika** [ludufre/capacitor-screenshot#3]

**Comment by ludufre** [comment]
Only iOS and Android. But, PRs are welcome.

**Comment by jipika** [comment]
I misdescribed it
Can you get a screenshot of the Launcher

**Comment by ludufre** [comment]
Which Launcher? 

It currently only works on iOS and Android. I believe that with Electron it would be possible, but it would need to be developed.

**Comment by jipika** [comment]
Screenshot of Android Launcher app

**Comment by jipika** [comment]
Not the currently active app

**Comment by ludufre** [comment]
Got it. I think it's not possible. I believe there is some plugin for screen recording.
