### ISSUE TITLE
not working correctly on Android

### ISSUE THREAD

**Issue by Saqib92** [ludufre/capacitor-screenshot#4]
Not working on android. It messes Up UI.

**Comment by Saqib92** [comment]
When taking screenshot on android it messed up complete UI, Also I am using `Fabricjs` and my canvas is not visible in screenshots. 
It is working fine in IOS.

**Comment by ludufre** [comment]
Hello. I was unable to reproduce the reported issue. In my tests, on Android it is working perfectly. Could you provide a simple repository with the problem so that I can debug?

**Comment by Saqib92** [comment]
check this repo:

https://github.com/Saqib92/ionic-fabricjs-editor

Steps to reproduce:

`git clone https://github.com/Saqib92/ionic-fabricjs-editor`

`npm i`

`npx cap run android`

click on bottom red button with + icon > click on open popover > click take screenshot. 
Issues: 
1). Bottom menu will be visible at bottom even after closing at the time of screenshot. 
2). Fabricjs Canvas not visible in screenshots (only in android).

**Comment by ludufre** [comment]
Indeed, native Android screenshot function cannot capture Canvas managed by FabricJs. This plugin just invokes the screenshot on Android's WebView. There is no custom code, just a screenshot. This is a deeper issue than this plugin and specifically related to FabricJS. I don't know how to help you in this case...

**Comment by Saqib92** [comment]
when i take screenshot natively from power button + volume button it works perfectly but not from plugin.  I suspect there might be a better option available for this.
